services:
  app:
    build: .
    working_dir: /app/shared
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./shared:/app/shared
      - ./input:/app/input:ro
      - ./output:/app/output
      - ./scripts/in_docker:/app/scripts:ro
    cap_drop:
      - ALL
